---
title: "..."
output: html_fragment
---

# Web Application User Guide

## Introduction

----

When the web application is launched from *Improving agricultural injury surveillance: comparing injuries captured Iowa’s Workers’ Compensation and trauma registry data*, one will be initially directed to a couple of user guides. The first guide, titled *Web Application User Guide* is this current page, provides a quick overview of the modeling framework and a detailed description of the inner workings of the application. Navigate to the *Modeling Framework* tab for see a more detailed description of the model construction and the calculations of the predicted probabilities. Access to the web application can be found in the *Web Application* tab. This application loads a [Posit Shiny](https://shiny.posit.co) application that calculates the predicted probabilities of being in Iowa's Workers' Compensation database and Iowa's Trauma Registry. Remaining information in this guides provides details on how the web  application works. First, a quick overview of the model used to calculate the predicted probabilities is provided to enhance the understanding of the application basics.

## Model overview

----

We developed a logistic regression model to probabilistically predict which data source captured an injured person, given their injury characteristics and demographics. The predictive model used explanatory variables found in both data sources: age, gender, injury cause, and injury nature, and modeled the event that an injured person’s information was recorded in the Workers’ Compensation data. For categorical predictors (gender, injury cause, and injury nature), we used effects coding instead of reference coding, so the average effect would be zero.

## Application launch

----

The *Web Application* tab launches the application to calculate the predicted probabilities of being in Iowa's Workers' Compensation database and Trauma Registry. The application has two panels. The left panel receives the input from the user, while the right panel displays the results based on the information given. For this application, predicted probabilities are calculated based on sex, age, and cause and nature of the injury. The starting values for sex, cause of injury, and nature of the injury are ***Average of effect***. This value is a by-product of effects coding in the modeling framework, allowing probabilities to be calculated while averaging all the possible values for the predictors. So, at any time, if one wants to obtain a predicted probability or a set of predicted probabilities while considering an average effect of a categorical variable, then select the ***Average of effect*** option for the variable of interest. Initially, the age of a person's is excluded in the probability calculation.

## Application Useage

----

### User inputs
The left panel of the application takes a select set of inputs from the user. There is a drop-down menu of all possible choices for the categorical variables (sex, cause of injury, and nature of injury). For the purpose of exploring the user inputs, consider the following example. Suppose one is interested in finding the predicted probability that a male who fell and fractured his arm is in the workers' compensation database. Then, all one would need to do is select ***Male*** in the **Sex** drop-down menu, ***Falls*** in the **Cause of Injury** drop-down menu, and ***Fractures/dislocation/sprains/strains*** in the **Nature of Injury** drop-down menu. Age is the only quantitative variable in the model and application. For specifying age, there are two age sliders titled **Minimum** and **Maximum Age** and a checkbox denoting whether age should be included in the probability calculation. If age is of interest, then there are several points to consider. First, the ***Include age in calculation of predicted probabilities*** checkbox must be selected. Second, the minimum and maximum age must be set to some value within the range of possible ages. By default, the minimum and maximum ages are set to 45, the mean and median age of the combined data sources. Suppose the two age sliders are assigned to different values, and the checkbox indicating whether multiple predicted probabilities should be calculated is not marked. In that case, the age used is the average of the minimum and maximum age selected. Next, to obtain a range of predicted probabilities over various ages, the ***Calculate multiple predicted probabilities*** checkbox must be selected, and the minimum and maximum ages must differ. The application will flip the two ages assigned in the background if the minimum age exceeds the maximum. Combining all the above steps for specifying injury characteristics and demographics will provide predicted probabilities specific to those characteristics of interest. 

### Results
Regardless of the injury characteristics and demographics specified in the user input panel, the results section (right panel) will have the same general setup. There will be columns denoting the data source of the injury case (`Source`), sex (`Sex`), cause of injury (`Cause`), nature of injury (`Nature`), age (`Age`), predicted probability (`Probability`), and $95\%$ Wald confidence interval (`LB` and `UB`). By default, sex, age, cause, and nature of the injury will have empty fields. This occurs because the categorical variables have initial values of ***Average of effect***, and age is not denoted to be included in the calculation. Probabilities for Iowa's Workers' Compensation database (`Workers' compensation`) and Trauma Registry (`Trauma registry`) are displayed for each probability calculation. As injury characteristics and demographics are defined, their associated columns in the results section will be filled in, and the probabilities (predicted and confidence interval) will be updated.


## On-device useage of web application

----

Currently, the web application does not allow the user to download the predicted probabilities calculated. Therefore, to obtain the probabilities for external use, installation of the `agstudy1app`,https://github.com/deboonstra/agstudy1app, package is required. Then, simply call the `agstudy1app::pred_prob()` function with the injury characteristics of interest. If one choose to run the web application on their local machine, they will need to `git clone` the [`agstudy1app`](https://github.com/deboonstra/agstudy1app) repository to their desired location. Then, in an interactive session of *R*, where `agstudy1app` is the current working directory, execute the following command.

```{r, eval = FALSE}
agstudy1app::launch()
```